# Generated by Django 3.1.7 on 2021-03-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210328_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_id',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
