# Generated by Django 3.1.2 on 2020-10-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
