# Generated by Django 3.1.1 on 2020-09-29 06:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CUSTOMER', 'Customer'), ('CASHIER', 'Cashier'), ('DATA_ENTRY_CLERK', 'Data Entry Clerk'), ('MANAGER', 'Manager'), ('SUBMANAGER', 'Sub Manager')], max_length=52, null=True),
        ),
    ]
