# Generated by Django 3.1.3 on 2020-11-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
