# Generated by Django 3.1.3 on 2020-11-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubManager',
        ),
        migrations.CreateModel(
            name='GeneralManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
