# Generated by Django 3.2 on 2021-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20210703_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subdomain',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
