# Generated by Django 3.2 on 2021-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20210708_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='subdomain',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
