# Generated by Django 3.2 on 2021-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='subdomain',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
