name: xshop-web-ci

on:
  push:
    branches: [develop, master]
  pull_request:

env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: github_actions
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  DEPLOY: TESTING
  PAYMOB_API_KEY: ${{ secrets.PAYMOB_API_KEY }}
  PAYMOB_IFRAME_ID: ${{ secrets.PAYMOB_IFRAME_ID }}
  PAYMOB_CARD_INTEGRATION_ID: ${{ secrets.PAYMOB_CARD_INTEGRATION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.6]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          POSTGRES_HOST: localhost

        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: collect static files
        run: poetry run python manage.py collectstatic --no-input
      - name: Run Tests
        run: poetry run python manage.py test
      - name: Run flake8 linter based on black
        run: poetry run flake8
